server:
  port: 8100
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysqqqqql01:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: nacos.zing.com
        namespace: 332cee00-5754-4138-8166-f2b562bec976
        cluster-name: local
        metadata:
          test: xxx
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: rocektmq-namesrv1:9876;rocektmq-namesrv1:9876
      bindings:
        input:
          destination: stream-test-topic
          # 如果用的是RocketMQ，一定要设置
          # 如果用的是其他MQ，可留空
          group: binder-group
        my-input:
          destination: stream-my-topic
          group: my-binder-group
        points-input:
          destination: points-topic
          group: points-binder-group
  zipkin:
    base-url: http://hadooooop:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率 默认0.1(10%)
      probability: 1.0
rocketmq:
  name-server: rocektmq-namesrv1:9876;rocektmq-namesrv1:9876
logging:
  level:
    org.springframework.cloud.sleuth: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always