server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos.zing.com
        namespace: 332cee00-5754-4138-8166-f2b562bec976
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: false
      default-filters:
        - AddResponseHeader=X-Foo, Default
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - TimeBetween=上午9:00,下午5:00
          filters:
            # AddRequestHeader {@link org.springframework.cloud.gateway.filter.NettyRoutingFilter#filter}
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a, b
            - RequestTime=true
        - id: blog_route
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
  zipkin:
    base-url: http://hadooooop:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率 默认0.1(10%)
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    org.springframework.boot.autoconfigure.web: debug
#    reactor.netty: debug
#    redisratelimiter: debug