server:
  port: 9100
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cyunzing/config-repo
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/