spring:
  rabbitmq:
    addresses: hadooooop
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 10000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true