server:
  port: 8762
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000